"""
The Consultancy Loop Orchestrator (Pro)
Diagnose (Research) -> Architect (Strategy) -> Report (Deliver)
"""

import sys
import os
import argparse
import json
from datetime import datetime
from research_client import research_prospect
from generate_strategy import generate_strategy

def save_markdown_report(company, strategy):
    """Generates a professional Markdown report"""
    
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"InnovLead_Strategy_{company.replace(' ', '_')}_{date_str}.md"
    output_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../outputs/proposals"))
    os.makedirs(output_dir, exist_ok=True)
    filepath = os.path.join(output_dir, filename)
    
    md_content = f"""# 🚀 Automation Strategy: {company.upper()}
**Date**: {date_str}
**Prepared by**: Antigravity (InnovLead Intelligence)

---

## 🎯 Executive Summary
{strategy.get('executive_summary', 'N/A')}

---

## 🔍 Key Findings
| Signal | Implication | Proposed Solution |
|--------|-------------|-------------------|
"""
    
    for item in strategy.get('analysis_matrix', []):
        md_content += f"| {item.get('signal')} | {item.get('implication')} | {item.get('solution')} |\n"
        
    md_content += """
---

## 💡 Top Automations Opportunities
"""
    
    for i, opp in enumerate(strategy.get('opportunities', []), 1):
        md_content += f"""### {i}. {opp.get('title')}
- **Problem**: {opp.get('pain_point')}
- **Solution**: {opp.get('proposed_solution')}
- **ROI Impact**: 💰 **{opp.get('roi_impact')}** (Confidence: {opp.get('confidence')})

"""

    md_content += f"""---

## ✉️ Draft Outreach (Email to CTO)
```text
{strategy.get('draft_email', 'No draft generated.')}
```

---
*Generated by Antigravity v1.0*
"""

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(md_content)
        
    return filepath

def run_loop(company_name: str):
    print(f"\n[START] CONSULTANCY LOOP FOR: {company_name}")
    print("="*60)
    
    # 1. DIAGNOSE
    print("\n[PHASE 1: DIAGNOSE]")
    try:
        research = research_prospect(company_name)
    except Exception as e:
        print(f"[ERROR] Research Failed: {e}")
        return
    
    # 2. ARCHITECT
    print("\n[PHASE 2: ARCHITECT]")
    try:
        strategy = generate_strategy(company_name, research)
    except Exception as e:
        print(f"[ERROR] Strategy Failed: {e}")
        return
    
    # 3. REPORT
    print("\n[PHASE 3: REPORT]")
    report_path = save_markdown_report(company_name, strategy)
    print(f"\n[SUCCESS] Strategy Report Generated:\n{report_path}")
    print("\n" + "="*60)
    print("Loop Complete. Ready to close.")

if __name__ == "__main__":
    if len(sys.argv) > 1:
        run_loop(sys.argv[1])
    else:
        print("Usage: py run_consultancy_loop.py 'Company Name'")
